AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# Fix for CodeUri issue on 2025-11-25
####
Resources:
  FilmRecommenderAnalyticsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FilmRecommender-Analytics-v2
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  FilmRecommenderDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "film-recommender-v2-dlq"
      MessageRetentionPeriod: 1209600

  FilmRecommenderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "film-recommender-v2-queue"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FilmRecommenderDLQ.Arn
        maxReceiveCount: 3

  FilmRecommenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt FilmRecommenderQueue.Arn
            
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:Scan
            Resource: !GetAtt FilmRecommenderAnalyticsTable.Arn

      Environment:
        Variables:
          RECOMMENDER_QUEUE_URL: !Ref FilmRecommenderQueue
      Events:
        RecommendApi:
          Type: Api
          Properties:
            Path: /api/recommend
            Method: POST
        AsyncRecommendApi:
          Type: Api
          Properties:
            Path: /api/recommend/async
            Method: POST
        StatusApi: 
          Type: Api
          Properties:
            Path: /api/recommend/status/{requestId}
            Method: GET
        AnalyticsApi:
          Type: Api
          Properties:
            Path: /api/analytics
            Method: GET
        HealthApi:
          Type: Api
          Properties:
            Path: /api/health
            Method: GET

  FilmRecommenderQueueProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "film-recommender-queue-processor"
      Runtime: python3.9
      Handler: queue_processor.lambda_handler
      CodeUri: lambda/src/
      Timeout: 300
      Policies:
        - SQSPollerPolicy:
            QueueName: !Ref FilmRecommenderQueue
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt FilmRecommenderAnalyticsTable.Arn

      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt FilmRecommenderQueue.Arn
            BatchSize: 5
      Environment:
        Variables:
          ECR_REPOSITORY: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/film-recommender"

Outputs:
  ApiUrl:
    Description: "API Gateway URL - Re-Deploy 18/11"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"